# Generated by Django 2.2.13 on 2021-02-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_auto_20210219_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyNews',
            new_name='MyNew',
        ),
        migrations.RenameField(
            model_name='mynew',
            old_name='newsType',
            new_name='newType',
        ),
    ]
