# Generated by Django 2.2.13 on 2021-02-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_auto_20210219_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynew',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='展报'),
        ),
    ]
